name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show content
      run: ls -al
    - uses: actions/setup-node@v1.1.0
    - name: Build
      run: |
        cd frontend
        npm run build
        cd ..
    - name: Move files
      run: |
        mkdir backend/dist
        mv frontend/dist/* backend/dist
    - uses: actions/heroku@1.0.0
    - name: Deploy to Heroku
      env: 
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: dmd-phase3
      run: |
        git init
        git add .
        git commit -m "Deploy to Heroku"
        git push -U https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
